spring:
  application:
    name: "backend" # "Maid in Korea"

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_REST_API_KEY}
            client-secret: ${KAKAO_REST_API_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/oauth/callback/kakao"
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: "https://kauth.kakao.com/oauth/authorize"
            token-uri: "https://kauth.kakao.com/oauth/token"
            user-info-uri: "https://kapi.kakao.com/v2/user/me"
            user-name-attribute: id

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC ???? ??? ??
    url: ${DB_URL} # jdbc:mysql://localhost:3306/{???????}
    username: ${DB_USER} # MySQL ?? ??
    password: ${DB_PW} # MySQL ????

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 2000ms
      repositories:
        enabled: false

  jpa:
    database: mysql # ??? ?????? ?? ?? (MySQL)
    database-platform: org.hibernate.dialect.MySQLDialect # Hibernate?? ??? MySQL ??(dialect) ??
    show-sql: true # ??? SQL ??? ??? ???? ?? ??
    hibernate:
      ddl-auto: update # ?????? ?? ? ?????? ???? ??? ??
    properties:
      hibernate:
        format_sql: true # ???? SQL ??? ?? ?? ???

jwt:
  token:
    secretKey: ${JWT_SECRET_KEY}
    expiration:
      access: 1800000
      refresh: 1209600000
